platform :ios, ’10.0’

target 'SwiftTools' do
# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'Alamofire'
pod 'Kingfisher'
pod “SwiftyJSON”
pod 'SnapKit'

end
